<form id="formaAltaPlaza">
	<label for="nombrePlaza">Nombre de la plaza</label> 
	<input placeholder="Nombre de la Plaza" type="text" name="nombre" id="nombrePlaza" /> 
	<label for="descripcionPlaza">Descripcion Plaza</label>
	<input placeholder="Descripcion de la plaza" type="text" name="descripcion" id="descripcionPlaza" /> 
	<label for="ciudadPlaza">Ciudad</label> 
	<input placeholder="Ciudad"	type="text" name="ciudad" id="ciudadPlaza" /> 
	<label for="estadoPlaza">Estado Plaza</label> 
	<select name="estado">
		<option value="">Selecciona Estado...</option>
		<option value="Aguascalientes">Aguascalientes</option>
		<option value="Baja California">Baja California</option>
		<option value="Baja California Sur">Baja California Sur</option>
		<option value="Campeche">Campeche</option>
		<option value="Coahuila">Coahuila de Zaragoza</option>
		<option value="Colima">Colima</option>
		<option value="Chiapas">Chiapas</option>
		<option value="Chihuahua">Chihuahua</option>
		<option value="DF">Distrito Federal</option>
		<option value="Durango">Durango</option>
		<option value="Guanajuato">Guanajuato</option>
		<option value="Guerrero">Guerrero</option>
		<option value="Hidalgo">Hidalgo</option>
		<option value="Jalisco">Jalisco</option>
		<option value="Mexico">Mexico</option>
		<option value="Michoacan">Michoacan de Ocampo</option>
		<option value="Morelos">Morelos</option>
		<option value="Nayarit">Nayarit</option>
		<option value="Nuevo Leon">Nuevo Leon</option>
		<option value="Oaxaca">Oaxaca</option>
		<option value="Puebla">Puebla</option>
		<option value="Queretaro">Queretaro</option>
		<option value="Quintana Roo">Quintana Roo</option>
		<option value="San Luis Potosi">San Luis Potosi</option>
		<option value="Sinaloa">Sinaloa</option>
		<option value="Sonora">Sonora</option>
		<option value="Tabasco">Tabasco</option>
		<option value="Tamaulipas">Tamaulipas</option>
		<option value="Tlaxcala">Tlaxcala</option>
		<option value="Veracruz">Veracruz</option>
		<option value="Yucatan">Yucatan</option>
		<option value="Zacatecas">Zacatecas</option>
	</select>
	<button class="button" onclick="enviarForma('Plazas','insert'); return false">Enviar</button>
	<button class="button" type="reset" value="Reset">Borrar Campos</button>
</form>





