<div class="w3-row" style="max-width: 750px; margin: 25px auto">
    <h3>Asociados</h3>
    <div class="w3-col l11">
        <table class="w3-table w3-centered">
            <tr class="w3-blue">
                <th>Código</th>
                <th>Nombre</th>
            </tr>
            <tbody>
            <?php
               foreach($result as $key => $row)
                    echo "<tr data-id='$row[CODIGO_ASOCIADO]'>
                        <td>$row[CODIGO_ASOCIADO]</td> 
                        <td>$row[NOMBRE]</td>
                    </tr>";
            ?>
            </tbody>
        </table>
    </div><!-- w3-col -->
    <div class="w3-col l1">
        <div class="w3-sidebar w3-bar-block" style="width:70px" >
            <a href="#" class="w3-bar-item w3-button" id="btnModalInsert"><i class="fa fa-plus-circle w3-xxlarge"></i></a> 
            <a href="#delete" class="w3-bar-item w3-button actionButtons"><i class="fa fa-times-circle w3-xxlarge"></i></a> 
            <a href="#update" class="w3-bar-item w3-button actionButtons"><i class="fa fa-edit w3-xxlarge"></i></a> 
            <a href="#consult" class="w3-bar-item w3-button actionButtons"><i class="fa fa-eye w3-xxlarge"></i></a>
            <a href="#" class="w3-bar-item w3-button" id="btnExport"><i class="fa fa-file-pdf-o w3-xxlarge"></i></a> 
        </div><!-- sidebar -->
    </div><!-- w3-col -->
</div><!-- w3-row -->
<div id="modalAlta" class="w3-modal">
    <div class="w3-modal-content">
        <header class="w3-container"> 
            <span onclick="document.getElementById('modalAlta').style.display='none'; inputsReset();" class="w3-button w3-display-topright">&times;</span>
            <h2 id="modalText"> </h2>
        </header>
        <div class="w3-container">
            <form id="formAlta">
                <p><b>Datos generales del asociado</b></p>
                <label>Nombres *</label>
                <input class="w3-input w3-border w3-hide inputForm" type="text" id="txtIdEdita" name="id">
                <input class="w3-input w3-border inputForm" type="text" id="txtNombre" name="nombre">
                <label>Apellido paterno *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtApellidoP" name="apellidoP">
                <label>Apellido materno *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtApellidoM" name="apellidoM">
                <label>Fecha de nacimiento *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtNacimiento" name="nacimiento">
                <label>Edad</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtEdad" name="edad">
                <label>Sexo *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtSexo" name="sexo">
                <p>Hijos *
                <input class="w3-check inputForm" type="checkbox" value="0" id="checkHijos" name="hijos"></p>
                <label>RFC *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtRFC" name="rfc">
                <label>CURP *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCURP" name="curp">
                <label>Lugar de nacimiento *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtLugarNacimiento" name="lugarNacimiento">
                <label>Nacionalidad *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtNacionalidad" name="nacionalidad">
                <label>Estado civil *</label>
                <input class="w3-input w3-border inputForm" type="text" id="checkEstadoCivil" name="estadoCivil">
                <p>Extranjero *
                <input class="w3-check inputForm" type="checkbox" value="0" id="checkExtranjero" name="extranjero"></p>
                <label>Correo electrónico *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCorreo" name="correo">
                <label>Teléfono *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtTelefono" name="telefono">
                <!--<label>CC *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCC" name="cc">-->

                <p><b>Domicilio del asociado</b></p>
                <label>Domicilio *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtDomicilio" name="domicilio">
                <label>Colonia *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtColonia" name="colonia">
                <label>Delegacion *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtDelegacion" name="delegacion">
                <label>Ciudad *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCiudad" name="ciudad">
                <label>Estado *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtEstado" name="estado">
                <label>Entre calles (calle 1) *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtEntreCalles" name="entreCalle1">
                <label>Entre calles (calle 2) *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtEntreCalles" name="entreCalle2">
                <label>CP *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCP" name="cp">
                <label>Domicilio fiscal *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtDomicilioFiscal" name="domicilioFiscal">
                <label>CP fiscal *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCPFiscal" name="cpFiscal">

                <p><b>Configuración para el sistema</b></p>
                <label>Fecha inicio *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtFechaInicio" name="fechaInicio">
                <label>Fecha baja *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtFechaBaja" name="fechaBaja">
                <!--<label>Causa *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCausa" name="causa">
                <label>% CO *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtCO" name="co">
                <label>Documentos completos *</label>
                <input class="w3-input w3-border inputForm" type="text" id="checkDocumentos" name="documentos">
                <label>Generar A *</label>
                <input class="w3-input w3-border inputForm" type="text" id="checkA" name="A">
                <label>Generar B *</label>
                <input class="w3-input w3-border inputForm" type="text" id="checkB" name="B">
                <label>Generar C *</label>
                <input class="w3-input w3-border inputForm" type="text" id="checkC" name="C">

                <p><b>Configuración de polizas</b></p>
                <label>Gastos médicos *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtGastosMedicosA" name="gastosMedicosA">
                <input class="w3-input w3-border inputForm" type="text" id="txtGastosMedicosB" name="gastosMedicosB">
                <input class="w3-input w3-border inputForm" type="text" id="txtGastosMedicosC" name="gastosMedicosC">
                <label>Seguro de vida *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtSeguroVidaA" name="seguroVidaA">
                <input class="w3-input w3-border inputForm" type="text" id="txtSeguroVidaB" name="seguroVidaB">
                <input class="w3-input w3-border inputForm" type="text" id="txtSeguroVidaC" name="seguroVidaC">

                <p><b>Configuración IMSS</b></p>
                <label>Numero *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtNumeroIMSS" name="numeroIMSS">
                <label>SD *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtSD" name="SD">
                <label>Días *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtDías" name="dias">
                <label>Comentario *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtComentarioIMSS" name="comentarioIMSS">
                <label>Infonavit *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtInfonavit" name="infonavit">
                <input class="w3-input w3-border inputForm" type="text" id="txtInfonavitNum" name="infonavitNum">-->

                <p><b>Configuración desarrollos</b></p>
                <label>Desarrollo actual *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtDesarrollo" name="desarrollo">
                <label>Puesto *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtPuesto" name="puesto">

                <!--<label>Banco y cuenta *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtBanco" name="banco">
                <label>Comentarios *</label>
                <input class="w3-input w3-border inputForm" type="text" id="txtComentarios" name="comentarios">-->
            </form>
            <button class="w3-button w3-green w3-block w3-margin-bottom" ></button>
        </div>
    </div>
</div><!-- w3-modal -->
<script>
    var inputs = document.getElementsByClassName("inputForm");
    
    $(document).ready(function(){
        /*$("#formAlta input").each(function(){
            $(this).val("RUBEN OMAR ROMANO");
        });*/
        
        $("tbody tr").click(function () {
            $('.selected').removeClass('selected');
            $(this).addClass("selected");
        });//tbody tr
        
        $(".actionButtons").click(function(e){
            e.preventDefault();
            var x = document.getElementsByClassName('selected');
            if(x.length === 0)
                alert("selecciona un tr");
            else
            {
                var action = $(this).attr('href').substring(1);
                var id = x[0].getAttribute("data-id");
                switch(action)
                {
                    case 'delete':
                        $.ajax({
                            type: "POST",
                            url: 'index.php',
                            data: {c:"Asociados", a:"delete", id:id},
                            success: function(response){
				$("#contenidos").html(response);
                            }//success
			});//ajax
                    break;
                    case 'update':
                    case 'consult':
                        $.ajax({
                            type: "POST",
                            url: 'index.php',
                            data: {c:"Asociados", a:"retrive", id:id},
                            success: function(response){
                                var obj = JSON.parse(response);
                                var idx = 0;
                                for (var i in obj)
                                {
                                    for (var j in obj[i])
                                    {
                                        if(action == 'consult')
                                            inputs[idx].disabled = true;
                                        if( $(inputs[idx]).is(":checkbox") )
                                        {
                                            if(obj[i][j] == 1)
                                                inputs[idx].checked = true;
                                            else
                                                inputs[idx].checked = false;
                                        }//if
                                        else
                                            inputs[idx].value =  obj[i][j];
                                        idx++;
                                    }//for
                                }//for
                                if(action == 'update')
                                {
                                    document.getElementById('modalText').innerText = "Edición de desarrollos";
                                    $("#modalAlta button").attr("onclick", "formActionButton('update')");
                                    $("#modalAlta button").text("Guardar").show();
                                }//if
                                else
                                {
                                    document.getElementById('modalText').innerText = "Consulta de desarrollos";
                                    $("#modalAlta button").hide();
                                }//else
                                document.getElementById('modalAlta').style.display = 'block';
                            }//success
			});//ajax
                    break;
                }//switch
            }//else
        });//actionButtons a
        
        $("#formAlta .w3-check").click( function(){
            if($(this).is(':checked'))
                $(this).attr('value', 1);
            else
                $(this).attr('value', 0);
        });//#formAlta .w3-check
        
        $("#btnModalInsert").click(function(){
            //inputsEnabled("insert");
            document.getElementById('modalText').innerText = "Alta de desarrollos";
            $("#modalAlta button").attr("onclick", "formActionButton('insert')");
            $("#modalAlta button").text("Agregar").show();
            document.getElementById('modalAlta').style.display = 'block';
        });//btnModalInsert
        
        $("#btnExport").click(function(){
            $.ajax({
                type: "POST",
                url: 'index.php',
                data: {c:"Asociados", a:"export"},
                success: function(){
                    window.open('public/files/asociados.pdf', '_blank');
                }//success
            });//ajax
        });//btnExport
    });//document
    
    function formActionButton(event){
        if(!emptyFields("modalAlta"))
        {
            var obj = $("#formAlta").serialize();
            if(!obj.includes("hijos"))
                obj += "&hijos=0";
            if(!obj.includes("extranjero"))
                obj += "&extranjero=0";
            $.ajax({
                type: "POST",
                url: "index.php",
                data: {str:obj, c:"Asociados", a:event},
                success: function(response){
                    $("#contenidos").html(response);
                }//success
            });//ajax
        }//if
        else
            alert("TODOS LOS CAMPOS SON OBLIGATORIOS.");
    }//formActionButton
            
    function inputsReset(){
        for(var i = 0; i < inputs.length; i++)
        {
            if($(inputs[i]).is(":checkbox"))
            {
                inputs[i].checked = false;
                inputs[i].value = 0;
            }//if
            else
                inputs[i].value = '';
            inputs[i].disabled = false;
        }//for
    }//inputsReset
    
    function emptyFields(parent){
        var bandera = false;
        $("#" + parent + " input").each(function() {
            if ($(this).val().trim() == "")
                bandera = true;
        });
        return bandera;
    }//emptyFields
</script>
<style>
    .selected {
	background-color: blue;
	color: white;
    }
</style>