<form id="formaEditarPlaza">
	<input type="hidden" name="id" id="idPlaza" value="<?php echo $plaza[0]['ID_PLAZA']; ?>"/> 
	<label for="nombre">Nombre	de la plaza</label> 
	<input placeholder="Nombre de la Plaza"	type="text" name="nombre" id="nombrePlaza" value="<?php echo $plaza[0]['NOMBRE'];?>" /> 
	<label for="descripcion">Descripcion Plaza</label> 
	<input placeholder="Descripcion de la plaza" type="text" name="descripcion" id="descripcionPlaza"  value="<?php echo $plaza[0]['DESCRIPCION'];?>" /> 
	<label for="ciudad">Ciudad</label>
	<input placeholder="Ciudad" type="text" name="ciudad" id="ciudadPlaza"  value="<?php echo $plaza[0]['CIUDAD'];?>" />
	<label for="estadoPlaza">EDO Plaza</label> 
	<select  name="estado">
		<option value="">Selecciona Estado...</option>
		<option value="Aguascalientes">Aguascalientes</option>
		<option value="Baja California">Baja California</option>
		<option value="Baja California Sur">Baja California Sur</option>
		<option value="Campeche">Campeche</option>
		<option value="Coahuila">Coahuila de Zaragoza</option>
		<option value="Colima">Colima</option>
		<option value="Chiapas">Chiapas</option>
		<option value="Chihuahua">Chihuahua</option>
		<option value="DF">Distrito Federal</option>
		<option value="Durango">Durango</option>
		<option value="Guanajuato">Guanajuato</option>
		<option value="Guerrero">Guerrero</option>
		<option value="Hidalgo">Hidalgo</option>
		<option value="Jalisco">Jalisco</option>
		<option value="M&eacute;xico">M&eacute;xico</option>
		<option value="Michoac&aacute;n">Michoac&aacute;n de Ocampo</option>
		<option value="Morelos">Morelos</option>
		<option value="Nayarit">Nayarit</option>
		<option value="Nuevo Le&oacute;n">Nuevo Le&oacute;n</option>
		<option value="Oaxaca">Oaxaca</option>
		<option value="Puebla">Puebla</option>
		<option value="Quer&eacute;taro">Quer&eacute;taro</option>
		<option value="Quintana Roo">Quintana Roo</option>
		<option value="San Luis Potos&iacute;">San Luis Potos&iacute;</option>
		<option value="Sinaloa">Sinaloa</option>
		<option value="Sonora">Sonora</option>
		<option value="Tabasco">Tabasco</option>
		<option value="Tamaulipas">Tamaulipas</option>
		<option value="Tlaxcala">Tlaxcala</option>
		<option value="Veracruz">Veracruz</option>
		<option value="Yucat&aacute;n">Yucat&aacute;n</option>
		<option value="Zacatecas">Zacatecas</option>
	</select>
	<button id="enviarEditar" onclick="updatePlaza(); return false"class="button">Enviar</button>
	<button class="button" type="reset" value="Reset">Borrar Campos</button>
</form>
 <script>

$('select').val("<?php echo $plaza[0]['ESTADO'];?>");

function updatePlaza(){
	var formaPlaza = new FormData($('#formaEditarPlaza')[0]);
		//alert(formaPlaza.length);
		
	var jsonData = {c:"Plazas", 
					a:"update",
					id: formaPlaza.get("id") , 
					nombre: formaPlaza.get("nombre") , 
					descripcion: formaPlaza.get("descripcion") , 
					ciudad:formaPlaza.get("ciudad") , 
					estado :  formaPlaza.get("estado")};
	$.ajax({
        type: "POST",
        url: "index.php",
        data: jsonData,
        success: function(response){
            $('#dialog').dialog("close");
            $("#contenidos").html(response);
        }//success
    });//ajax
	
	}			


 </script>




