<form class="w3-container w3-margin-top">
	<label>Usuario</label>
	<input type="text" id="txtUsuario">
	<label>Password</label>
	<input type="text" id="txtPassword">
	<label>Sistemas</label>
	<input type="text" id="txtSistemas">
	<button class="w3-button w3-green" id="btnAgregar">Agregar</button>
</form>
<table class="w3-table-all w3-centered" style="max-width: 1000px; margin: 25px auto">
	<tr class="w3-blue">
		<th>Usuario</th>
		<th>Password</th>
		<th>Status</th>
		<th>Sistemas</th>
		<th>Delete</th>
		<th>Update</th>
	</tr>
	<tbody>
		<tr>
		<?php
			foreach($usuarios as $key => $row)
				echo "<tr>
					<td><input type='text' class='w3-input w3-border' value='$row[usuario]'</td> 
					<td><input type='text' class='w3-input w3-border' value='$row[password]'</td>
					<td><input type='text' class='w3-input w3-border' value='$row[status]'</td>
					<td><input type='text' class='w3-input w3-border' value='$row[sistemas]'</td> 
					<td><button class='w3-button w3-red delete' data-idx='$row[id_usuario]' data-a='delete'> DELETE </button></td>
					<td><button class='w3-button w3-green update' data-idx='$row[id_usuario]' data-a='update'> UPDATE </button></td>
				</tr>";
		?>
		</tr>
	</tbody>
</table>
<script>
	$(document).ready(function(){
		$('#btnAgregar').click(function(e){
			e.preventDefault();
			var usuario = $('#txtUsuario').val();
			var password = $('#txtPassword').val();
			var sistemas = $('#txtSistemas').val();
			$.ajax({
				type: "POST",
				url: 'index.php',
				data: {c:"Usuarios", a:"insert", usuario:usuario, password:password, sistemas:sistemas},
				success: function(response){
					//alert(response);
					$("#contenidos").html(response);
				}
			});//ajax
		});//btnAgregar

		$('.delete').click(function(){
			var idx = $(this).attr('data-idx');
			$.ajax({
				type: "POST",
				url: 'index.php',
				data: {c:"Usuarios", a:"delete", idx:idx},
				success: function(response){
					$("#contenidos").html(response);
				}
			});//ajax
		});//table button

		$('.update').click(function(){
			var idx = $(this).attr('data-idx');
			var array = [];
			$(this).closest('tr').find("input").each(function(){
        		array.push(this.value);
    		});//closest input
			$.ajax({
				type: "POST",
				url: 'index.php',
				data: {c:"Usuarios", a:"update", idx:idx, usuario:array[0], password:array[1], status:array[2], sistemas:array[3]},
				success: function(response){
					$("#contenidos").html(response);
				}
			});//ajax
		});//table button
	});//ready
</script>